version: '3.8'

services:
  mongodb:
    image: mongo:8.0.4
    container_name: review-service-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: reviewDb
    volumes:
      - mongodb_data:/data/db
    networks:
      - review-network

volumes:
  mongodb_data:

networks:
  review-network:
    driver: bridge
